XLite\Model\Config:
  - name: webhook_token
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 10
    translations:
      - code: en
        option_name: "Webhook token"
  - name: store_path
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 20
    translations:
      - code: en
        option_name: "File store path"
  - name: owner_id
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 30
    translations:
      - code: en
        option_name: "Owner ID"
  - name: deleted_product_id
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 40
    translations:
      - code: en
        option_name: "Deleted Product Placeholder ID"
        option_comment: "This is a placeholder product used when an item in an order has been deleted from the shopping cart. It ensures the order can be processed without missing line items."
  - name: debug_enabled
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Checkbox\OnOffWithoutOffLabel
    orderby: 50
    translations:
      - code: en
        option_name: "Enable debugging"
  - name: orders_from_number
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text\Integer
    orderBy: 60
    value: 0
    translations:
      - code: en
        option_name: "Start sync from order number (0 - no limit)"
  - name: orders_enable_sync
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Checkbox\OnOffWithoutOffLabel
    orderBy: 70
    value: false
    translations:
      - code: en
        option_name: "Enable order synchronization"
  - name: zoho_url
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderBy: 80
    value: false
    translations:
      - code: en
        option_name: "Zoho Url"
  - name: deals_from_date
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text\Date
    orderBy: 90
    value: 0
    translations:
      - code: en
        option_name: "Start sync Deals from"
