XLite\Model\Config:
  - name: store_path
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 0
    translations:
      - code: en
        option_name: "File store path"
  - name: owner_id
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 100
    translations:
      - code: en
        option_name: "Owner ID"
  - name: deleted_product_id
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text
    orderby: 150
    translations:
      - code: en
        option_name: "Deleted Product Placeholder ID"
        option_comment: 'This is a placeholder product used when an item in an order has been deleted from the shopping cart. It ensures the order can be processed without missing line items.'
  - name: debug_enabled
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Checkbox\OnOffWithoutOffLabel
    orderby: 200
    translations:
      - code: en
        option_name: "Enable debugging"
  - name: orders_from_number
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Text\Integer
    orderBy: 250
    value: 0
    translations:
      - code: en
        option_name: "Start sync from order number (0 - no limit)"
  - name: orders_enable_sync
    category: Iidev\ZohoCRM
    type: XLite\View\FormField\Input\Checkbox\OnOffWithoutOffLabel
    orderBy: 300
    value: false
    translations:
      - code: en
        option_name: "Enable order synchronization"