#
# Module services
#

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  handler:
    class: Iidev\ZohoCRM\Messenger\Handler\ExportHandler
    tags:
      - { name: messenger.message_handler, transport: async }

  Iidev\ZohoCRM\Messenger\Handler\ExportHandler:
    tags:
      - name: messenger.message_handler
        handles: Iidev\ZohoCRM\Messenger\Message\ExportMessage

  # Dispatcher

  Iidev\ZohoCRM\Core\Dispatcher\Products\CreateProductsDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Products\CreateProductVariantsDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Products\UpdateProductsDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Products\UpdateProductVariantsDispatcher: ~

  Iidev\ZohoCRM\Core\Dispatcher\Profiles\CreateProfilesDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Profiles\UpdateProfilesDispatcher: ~

  Iidev\ZohoCRM\Core\Dispatcher\Orders\CreateOrdersDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Orders\UpdateOrdersDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Orders\CreateOrderMessagesDispatcher: ~

  Iidev\ZohoCRM\Core\Dispatcher\Quotes\CreateQuotesDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Quotes\UpdateQuotesDispatcher: ~

  Iidev\ZohoCRM\Core\Dispatcher\Deals\CreateDealsDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\Deals\UpdateDealsDispatcher: ~

  # CommandFactory

  Iidev\ZohoCRM\Core\Factory\Commands\Products\PushProductsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Products\PushProductVariantsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Products\UpdateProductsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Products\UpdateProductVariantsCommandFactory:

  Iidev\ZohoCRM\Core\Factory\Commands\Profiles\PushProfilesCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Profiles\UpdateProfilesCommandFactory:

  Iidev\ZohoCRM\Core\Factory\Commands\Orders\PushOrdersCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Orders\UpdateOrdersCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Orders\PushOrderMessagesCommandFactory:

  Iidev\ZohoCRM\Core\Factory\Commands\Quotes\PushQuotesCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Quotes\UpdateQuotesCommandFactory:

  Iidev\ZohoCRM\Core\Factory\Commands\Deals\PushDealsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Deals\UpdateDealsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\Deals\UpdateClosedDealsCommandFactory:

  # Task

  Iidev\ZohoCRM\Core\Task\Products\CreateProducts:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }
  
  Iidev\ZohoCRM\Core\Task\Products\CreateProductVariants:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Products\UpdateProducts:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Products\UpdateProductVariants:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Profiles\CreateProfiles:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }
  
  Iidev\ZohoCRM\Core\Task\Profiles\UpdateProfiles:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Quotes\CreateQuotes:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Quotes\UpdateQuotes:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Orders\CreateOrders:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Orders\UpdateOrders:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\Orders\CreateOrderMessages:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }
  
  Iidev\ZohoCRM\Core\Task\Deals\CreateDeals:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }
  
  Iidev\ZohoCRM\Core\Task\Deals\UpdateDeals:
    tags:
      - {
          name: kernel.event_listener,
          event: zoho.cronjob,
          method: handleTask,
        }

  # Command

  Iidev\ZohoCRM\Command\CronCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:Cron" }
  
  Iidev\ZohoCRM\Command\Products\CreateProductsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateProducts" }

  Iidev\ZohoCRM\Command\Products\CreateProductVariantsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateProductVariants" }

  Iidev\ZohoCRM\Command\Products\UpdateProductsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateProducts" }

  Iidev\ZohoCRM\Command\Products\UpdateProductVariantsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateProductVariants" }

  Iidev\ZohoCRM\Command\Profiles\CreateProfilesCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateProfiles" }
  
  Iidev\ZohoCRM\Command\Profiles\UpdateProfilesCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateProfiles" }

  Iidev\ZohoCRM\Command\Orders\CreateOrdersCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateOrders" }

  Iidev\ZohoCRM\Command\Orders\UpdateOrdersCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateOrders" }

  Iidev\ZohoCRM\Command\Orders\CreateOrderMessagesCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateOrderMessages" }

  Iidev\ZohoCRM\Command\Quotes\CreateQuotesCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateQuotes" }

  Iidev\ZohoCRM\Command\Quotes\UpdateQuotesCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateQuotes" }
  
  Iidev\ZohoCRM\Command\Deals\CreateDealsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateDeals" }
  
  Iidev\ZohoCRM\Command\Deals\UpdateDealsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateDeals" }
