#
# Module services
#

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  handler:
    class: Iidev\ZohoCRM\Messenger\Handler\ExportHandler
    tags:
      - { name: messenger.message_handler, transport: async }

  Iidev\ZohoCRM\Messenger\Handler\ExportHandler:
    tags:
      - name: messenger.message_handler
        handles: Qualiteam\SkinActSkuVault\Messenger\Message\ExportMessage

  Iidev\ZohoCRM\Core\Dispatcher\CreateProductsDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\UpdateProductsDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\CreateProfilesDispatcher: ~
  Iidev\ZohoCRM\Core\Dispatcher\CreateOrdersDispatcher: ~

  Iidev\ZohoCRM\Core\Factory\Commands\PushProductsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\UpdateProductsCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\PushProfilesCommandFactory:
  Iidev\ZohoCRM\Core\Factory\Commands\PushOrdersCommandFactory:

  Iidev\ZohoCRM\Core\Task\CreateProducts:
    tags:
      - {
          name: kernel.event_listener,
          event: xcart.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\UpdateProducts:
    tags:
      - {
          name: kernel.event_listener,
          event: xcart.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\CreateProfiles:
    tags:
      - {
          name: kernel.event_listener,
          event: xcart.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Core\Task\CreateOrders:
    tags:
      - {
          name: kernel.event_listener,
          event: xcart.cronjob,
          method: handleTask,
        }

  Iidev\ZohoCRM\Command\CreateProductsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateProducts" }

  Iidev\ZohoCRM\Command\UpdateProductsCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:UpdateProducts" }

  Iidev\ZohoCRM\Command\CreateProfilesCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateProfiles" }

  Iidev\ZohoCRM\Command\CreateOrdersCommand:
    tags:
      - { name: "console.command", command: "ZohoCRM:CreateOrders" }